// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: customers.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Customer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCustomerReq) Reset() {
	*x = AddCustomerReq{}
	mi := &file_customers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerReq) ProtoMessage() {}

func (x *AddCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerReq.ProtoReflect.Descriptor instead.
func (*AddCustomerReq) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{1}
}

func (x *AddCustomerReq) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type AddCustomerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCustomerRes) Reset() {
	*x = AddCustomerRes{}
	mi := &file_customers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCustomerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerRes) ProtoMessage() {}

func (x *AddCustomerRes) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerRes.ProtoReflect.Descriptor instead.
func (*AddCustomerRes) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{2}
}

func (x *AddCustomerRes) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerReq) Reset() {
	*x = UpdateCustomerReq{}
	mi := &file_customers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerReq) ProtoMessage() {}

func (x *UpdateCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerReq.ProtoReflect.Descriptor instead.
func (*UpdateCustomerReq) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCustomerReq) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateCustomerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRes) Reset() {
	*x = UpdateCustomerRes{}
	mi := &file_customers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRes) ProtoMessage() {}

func (x *UpdateCustomerRes) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRes.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRes) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCustomerRes) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type ListCustomersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersReq) Reset() {
	*x = ListCustomersReq{}
	mi := &file_customers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersReq) ProtoMessage() {}

func (x *ListCustomersReq) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersReq.ProtoReflect.Descriptor instead.
func (*ListCustomersReq) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{5}
}

type ListCustomersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRes) Reset() {
	*x = ListCustomersRes{}
	mi := &file_customers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRes) ProtoMessage() {}

func (x *ListCustomersRes) ProtoReflect() protoreflect.Message {
	mi := &file_customers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRes.ProtoReflect.Descriptor instead.
func (*ListCustomersRes) Descriptor() ([]byte, []int) {
	return file_customers_proto_rawDescGZIP(), []int{6}
}

func (x *ListCustomersRes) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

var File_customers_proto protoreflect.FileDescriptor

const file_customers_proto_rawDesc = "" +
	"\n" +
	"\x0fcustomers.proto\x12\tcustomers\"\x80\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"A\n" +
	"\x0eAddCustomerReq\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.customers.CustomerR\bcustomer\"A\n" +
	"\x0eAddCustomerRes\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.customers.CustomerR\bcustomer\"D\n" +
	"\x11UpdateCustomerReq\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.customers.CustomerR\bcustomer\"D\n" +
	"\x11UpdateCustomerRes\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.customers.CustomerR\bcustomer\"\x12\n" +
	"\x10ListCustomersReq\"E\n" +
	"\x10ListCustomersRes\x121\n" +
	"\tcustomers\x18\x01 \x03(\v2\x13.customers.CustomerR\tcustomers2\xef\x01\n" +
	"\x0fCustomerService\x12I\n" +
	"\rListCustomers\x12\x1b.customers.ListCustomersReq\x1a\x1b.customers.ListCustomersRes\x12C\n" +
	"\vAddCustomer\x12\x19.customers.AddCustomerReq\x1a\x19.customers.AddCustomerRes\x12L\n" +
	"\x0eUpdateCustomer\x12\x1c.customers.UpdateCustomerReq\x1a\x1c.customers.UpdateCustomerResB\x12Z\x10server/customersb\x06proto3"

var (
	file_customers_proto_rawDescOnce sync.Once
	file_customers_proto_rawDescData []byte
)

func file_customers_proto_rawDescGZIP() []byte {
	file_customers_proto_rawDescOnce.Do(func() {
		file_customers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_proto_rawDesc), len(file_customers_proto_rawDesc)))
	})
	return file_customers_proto_rawDescData
}

var file_customers_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_customers_proto_goTypes = []any{
	(*Customer)(nil),          // 0: customers.Customer
	(*AddCustomerReq)(nil),    // 1: customers.AddCustomerReq
	(*AddCustomerRes)(nil),    // 2: customers.AddCustomerRes
	(*UpdateCustomerReq)(nil), // 3: customers.UpdateCustomerReq
	(*UpdateCustomerRes)(nil), // 4: customers.UpdateCustomerRes
	(*ListCustomersReq)(nil),  // 5: customers.ListCustomersReq
	(*ListCustomersRes)(nil),  // 6: customers.ListCustomersRes
}
var file_customers_proto_depIdxs = []int32{
	0, // 0: customers.AddCustomerReq.customer:type_name -> customers.Customer
	0, // 1: customers.AddCustomerRes.customer:type_name -> customers.Customer
	0, // 2: customers.UpdateCustomerReq.customer:type_name -> customers.Customer
	0, // 3: customers.UpdateCustomerRes.customer:type_name -> customers.Customer
	0, // 4: customers.ListCustomersRes.customers:type_name -> customers.Customer
	5, // 5: customers.CustomerService.ListCustomers:input_type -> customers.ListCustomersReq
	1, // 6: customers.CustomerService.AddCustomer:input_type -> customers.AddCustomerReq
	3, // 7: customers.CustomerService.UpdateCustomer:input_type -> customers.UpdateCustomerReq
	6, // 8: customers.CustomerService.ListCustomers:output_type -> customers.ListCustomersRes
	2, // 9: customers.CustomerService.AddCustomer:output_type -> customers.AddCustomerRes
	4, // 10: customers.CustomerService.UpdateCustomer:output_type -> customers.UpdateCustomerRes
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_customers_proto_init() }
func file_customers_proto_init() {
	if File_customers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_proto_rawDesc), len(file_customers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customers_proto_goTypes,
		DependencyIndexes: file_customers_proto_depIdxs,
		MessageInfos:      file_customers_proto_msgTypes,
	}.Build()
	File_customers_proto = out.File
	file_customers_proto_goTypes = nil
	file_customers_proto_depIdxs = nil
}
